app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: "%app_locales%"
    defaults:
        _locale: "%locale%"

noNeedPrefix:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
