# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    slugger:
        class: AppBundle\Utils\Slugger

    markdown:
        class: AppBundle\Utils\Markdown

    app.twig.app_extension:
            class: AppBundle\Twig\AppExtension
            arguments: ["@markdown", "%app_locales%"]
            public: false
            tags:
                - { name: twig.extension }

    app.twig.intl_extension:
            public: false
            class:  Twig_Extensions_Extension_Intl
            tags:
                - { name: twig.extension }

    app.redirect_to_preferred_locale_listener:
            class: AppBundle\EventListener\RedirectToPreferredLocaleListener
            arguments: ["@router", "%app_locales%", "%locale%"]
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
